# Generated by Django 3.1.6 on 2021-03-14 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'VERIFIED'), (3, 'EXTRACTED'), (4, 'PACKAGED'), (5, 'DECODED'), (6, 'CANCELED')])),
                ('location', models.IntegerField(choices=[(1, 'GENETICA'), (2, 'HANOI_LAB'), (3, 'SHIPPING_DEPARTMENT'), (4, 'USA_LAB')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Created at.', verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='GeneActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Created at.', verbose_name='created at')),
                ('type', models.IntegerField(choices=[(0, 'PENDING_AT_GENETICA'), (1, 'VERIFY'), (2, 'EXTRACT'), (3, 'PACKAGE'), (4, 'DECODE'), (5, 'SEND_TO_GENETICA'), (6, 'SEND_TO_HANOI_LAB'), (7, 'SEND_TO_USA_LAB'), (8, 'SEND_TO_SHIPPING'), (9, 'CANCEL')])),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(default='Created by someone', max_length=100)),
                ('attempts', models.IntegerField(default=1)),
                ('gene_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.gene')),
            ],
        ),
    ]
